- hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - name: find CentOS version
      shell: cat /etc/redhat-release | awk '{ print $4; }'
      register: centos_version

    - name: find Kubernetes version
      shell: kubectl get nodes | grep master | awk '{ print $5; }'
      register: kubernetes_version

    - name: find KubeVirt version
      shell: |
        cat kubevirt-ansible/vars/all.yml  |
        grep version | grep -v openshift | awk '{ print $2 }'
      register: kubevirt_version

    - name: template motd file
      template:
        src: motd.j2
        dest: /etc/motd
